/**
 *
 * $Id$
 */
package org.eclipse.emf.ecore.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.EModelElement;
import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link org.eclipse.emf.ecore.EAnnotation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EAnnotationValidator {
	boolean validate();

	boolean validateSource(String value);
	boolean validateDetails(EMap<String, String> value);
	boolean validateEModelElement(EModelElement value);
	boolean validateContents(EList<EObject> value);
	boolean validateReferences(EList<EObject> value);
}
