/**
 *
 * $Id$
 */
package org.eclipse.emf.ecore.validation;

import org.eclipse.emf.ecore.EPackage;

/**
 * A sample validator interface for {@link org.eclipse.emf.ecore.EFactory}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EFactoryValidator {
	boolean validate();

	boolean validateEPackage(EPackage value);
}
