/**
 *
 * $Id$
 */
package org.eclipse.emf.ecore.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClassifier;
import org.eclipse.emf.ecore.EGenericType;
import org.eclipse.emf.ecore.ETypeParameter;

/**
 * A sample validator interface for {@link org.eclipse.emf.ecore.EGenericType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EGenericTypeValidator {
	boolean validate();

	boolean validateEUpperBound(EGenericType value);
	boolean validateETypeArguments(EList<EGenericType> value);
	boolean validateERawType(EClassifier<?> value);
	boolean validateELowerBound(EGenericType value);
	boolean validateETypeParameter(ETypeParameter value);
	boolean validateEClassifier(EClassifier<?> value);
}
