/**
 *
 * $Id$
 */
package org.eclipse.emf.ecore.validation;

import org.eclipse.emf.ecore.EClassifier;
import org.eclipse.emf.ecore.EGenericType;

/**
 * A sample validator interface for {@link org.eclipse.emf.ecore.ETypedElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ETypedElementValidator {
	boolean validate();

	boolean validateOrdered(boolean value);
	boolean validateUnique(boolean value);
	boolean validateLowerBound(int value);
	boolean validateUpperBound(int value);
	boolean validateMany(boolean value);
	boolean validateRequired(boolean value);
	boolean validateEType(EClassifier<Object> value);
	boolean validateEGenericType(EGenericType value);
}
