/**
 *
 * $Id$
 */
package org.eclipse.emf.test.databinding.emfdb.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.test.databinding.emfdb.E;

/**
 * A sample validator interface for {@link org.eclipse.emf.test.databinding.emfdb.D}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DValidator
{
  boolean validate();

  boolean validateElist(EList<E> value);
  boolean validateName(String value);
}
