<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore" nsURI="http://www.eclipse.org/emf/2002/Ecore" nsPrefix="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="EAttribute">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ConsistentTransient"/>
    </eAnnotations>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//EObject"/>
    </eTypeParameters>
    <eTypeParameters name="V"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iD" eType="#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAttributeType" lowerBound="1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//EDataType">
        <eTypeArguments eTypeParameter="#//EAttribute/V"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//EStructuralFeature">
      <eTypeArguments eTypeParameter="#//EAttribute/C"/>
      <eTypeArguments eTypeParameter="#//EAttribute/V"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAnnotation" eSuperTypes="#//EModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="WellFormedSourceURI"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//EStringToStringMapEntry" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eModelElement" eType="#//EModelElement"
        transient="true" resolveProxies="false" eOpposite="#//EModelElement/eAnnotations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//EObject" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="InterfaceIsAbstract AtMostOneID UniqueFeatureNames UniqueOperationSignatures NoCircularSuperTypes WellFormedMapEntryClass ConsistentSuperTypes DisjointFeatureAndOperationSignatures"/>
    </eAnnotations>
    <eTypeParameters name="T">
      <eBounds eClassifier="#//EObject"/>
    </eTypeParameters>
    <eOperations name="isSuperTypeOf" eType="#//EBoolean">
      <eParameters name="someClass">
        <eGenericType eClassifier="#//EClass">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getFeatureCount" eType="#//EInt"/>
    <eOperations name="getEStructuralFeature">
      <eGenericType eClassifier="#//EStructuralFeature">
        <eTypeArguments eTypeParameter="#//EClass/T"/>
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="featureID" eType="#//EInt"/>
    </eOperations>
    <eOperations name="getFeatureID" eType="#//EInt">
      <eParameters name="feature">
        <eGenericType eClassifier="#//EStructuralFeature">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getEStructuralFeature">
      <eGenericType eClassifier="#//EStructuralFeature">
        <eTypeArguments eTypeParameter="#//EClass/T"/>
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="featureName" eType="#//EString"/>
    </eOperations>
    <eOperations name="getOperationCount" eType="#//EInt"/>
    <eOperations name="getEOperation">
      <eGenericType eClassifier="#//EOperation">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="operationID" eType="#//EInt"/>
    </eOperations>
    <eOperations name="getOperationID" eType="#//EInt">
      <eParameters name="operation">
        <eGenericType eClassifier="#//EOperation">
          <eTypeArguments>
            <eLowerBound eTypeParameter="#//EClass/T"/>
          </eTypeArguments>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getOverride">
      <eGenericType eClassifier="#//EOperation">
        <eTypeArguments eTypeParameter="#//EClass/T"/>
        <eTypeArguments>
          <eUpperBound eTypeParameter="#//EClass/getOverride/V"/>
        </eTypeArguments>
      </eGenericType>
      <eTypeParameters name="V"/>
      <eParameters name="operation">
        <eGenericType eClassifier="#//EOperation">
          <eTypeArguments/>
          <eTypeArguments eTypeParameter="#//EClass/getOverride/V"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getFeatureType" eType="#//EGenericType">
      <eParameters name="feature">
        <eGenericType eClassifier="#//EStructuralFeature">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" eType="#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eSuperTypes" upperBound="-1"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
        <details key="suppressedUnsetVisibility" value="true"/>
      </eAnnotations>
      <eGenericType eClassifier="#//EClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eOperations" upperBound="-1"
        containment="true" resolveProxies="false" eOpposite="#//EOperation/eContainingClass">
      <eGenericType eClassifier="#//EOperation">
        <eTypeArguments eTypeParameter="#//EClass/T"/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllAttributes" upperBound="-1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//EAttribute">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllReferences" upperBound="-1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//EReference">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eReferences" upperBound="-1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//EReference">
        <eTypeArguments eTypeParameter="#//EClass/T"/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAttributes" upperBound="-1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//EAttribute">
        <eTypeArguments eTypeParameter="#//EClass/T"/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllContainments" upperBound="-1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//EReference">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllOperations" upperBound="-1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//EOperation">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllStructuralFeatures"
        upperBound="-1" changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//EStructuralFeature">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllSuperTypes" upperBound="-1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//EClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eIDAttribute" changeable="false"
        volatile="true" transient="true" derived="true" resolveProxies="false">
      <eGenericType eClassifier="#//EAttribute">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eStructuralFeatures" upperBound="-1"
        containment="true" resolveProxies="false" eOpposite="#//EStructuralFeature/eContainingClass">
      <eGenericType eClassifier="#//EStructuralFeature">
        <eTypeArguments eTypeParameter="#//EClass/T"/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGenericSuperTypes" upperBound="-1"
        eType="#//EGenericType" unsettable="true" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
        <details key="suppressedUnsetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllGenericSuperTypes"
        upperBound="-1" eType="#//EGenericType" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eGenericSuperTypes eClassifier="#//EClassifier">
      <eTypeArguments eTypeParameter="#//EClass/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClassifier" abstract="true" eSuperTypes="#//ENamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="WellFormedInstanceTypeName UniqueTypeParameterNames"/>
    </eAnnotations>
    <eTypeParameters name="T"/>
    <eOperations name="isInstance" eType="#//EBoolean">
      <eParameters name="object" eType="#//EJavaObject"/>
    </eOperations>
    <eOperations name="getClassifierID" eType="#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceClassName" eType="#//EString"
        volatile="true" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
        <details key="suppressedUnsetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceClass" changeable="false"
        volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//EJavaClass">
        <eTypeArguments eTypeParameter="#//EClassifier/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" changeable="false"
        volatile="true" transient="true" derived="true">
      <eGenericType eTypeParameter="#//EClassifier/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceTypeName" eType="#//EString"
        volatile="true" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
        <details key="suppressedUnsetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" eType="#//EPackage"
        changeable="false" transient="true" eOpposite="#//EPackage/eClassifiers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeParameters" upperBound="-1"
        eType="#//ETypeParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDataType">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serializable" eType="#//EBoolean"
        defaultValueLiteral="true"/>
    <eGenericSuperTypes eClassifier="#//EClassifier">
      <eTypeArguments eTypeParameter="#//EDataType/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEnum">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueEnumeratorNames UniqueEnumeratorLiterals"/>
    </eAnnotations>
    <eTypeParameters name="T"/>
    <eOperations name="getEEnumLiteral" eType="#//EEnumLiteral">
      <eParameters name="name" eType="#//EString"/>
    </eOperations>
    <eOperations name="getEEnumLiteral" eType="#//EEnumLiteral">
      <eParameters name="value" eType="#//EInt"/>
    </eOperations>
    <eOperations name="getEEnumLiteralByLiteral" eType="#//EEnumLiteral">
      <eParameters name="literal" eType="#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eLiterals" upperBound="-1"
        eType="#//EEnumLiteral" containment="true" resolveProxies="false" eOpposite="#//EEnumLiteral/eEnum"/>
    <eGenericSuperTypes eClassifier="#//EDataType">
      <eTypeArguments eTypeParameter="#//EEnum/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEnumLiteral" eSuperTypes="#//ENamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instance" eType="#//EEnumerator"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eEnum" changeable="false"
        transient="true" resolveProxies="false" eOpposite="#//EEnum/eLiterals">
      <eGenericType eClassifier="#//EEnum">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFactory" eSuperTypes="#//EModelElement">
    <eOperations name="create">
      <eGenericType eTypeParameter="#//EFactory/create/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//EObject"/>
      </eTypeParameters>
      <eParameters name="eClass">
        <eGenericType eClassifier="#//EClass">
          <eTypeArguments eTypeParameter="#//EFactory/create/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="createFromString">
      <eGenericType eTypeParameter="#//EFactory/createFromString/T"/>
      <eTypeParameters name="T"/>
      <eParameters name="eDataType">
        <eGenericType eClassifier="#//EDataType">
          <eTypeArguments eTypeParameter="#//EFactory/createFromString/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="literalValue" eType="#//EString"/>
    </eOperations>
    <eOperations name="convertToString" eType="#//EString">
      <eTypeParameters name="T"/>
      <eParameters name="eDataType">
        <eGenericType eClassifier="#//EDataType">
          <eTypeArguments eTypeParameter="#//EFactory/convertToString/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="instanceValue">
        <eGenericType eTypeParameter="#//EFactory/convertToString/T"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" lowerBound="1"
        eType="#//EPackage" transient="true" resolveProxies="false" eOpposite="#//EPackage/eFactoryInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EModelElement" abstract="true">
    <eOperations name="getEAnnotation" eType="#//EAnnotation">
      <eParameters name="source" eType="#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAnnotations" upperBound="-1"
        eType="#//EAnnotation" containment="true" resolveProxies="false" eOpposite="#//EAnnotation/eModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENamedElement" abstract="true" eSuperTypes="#//EModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="WellFormedName"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObject">
    <eOperations name="eClass">
      <eGenericType eClassifier="#//EClass">
        <eTypeArguments>
          <eUpperBound eClassifier="#//EObject"/>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eOperations name="eIsProxy" eType="#//EBoolean"/>
    <eOperations name="eResource" eType="#//EResource"/>
    <eOperations name="eContainer" eType="#//EObject"/>
    <eOperations name="eContainingFeature">
      <eGenericType eClassifier="#//EStructuralFeature">
        <eTypeArguments>
          <eUpperBound eClassifier="#//EObject"/>
        </eTypeArguments>
        <eTypeArguments>
          <eUpperBound eClassifier="#//EObject"/>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eOperations name="eContainmentFeature">
      <eGenericType eClassifier="#//EReference">
        <eTypeArguments>
          <eUpperBound eClassifier="#//EObject"/>
        </eTypeArguments>
        <eTypeArguments>
          <eUpperBound eClassifier="#//EObject"/>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eOperations name="eContents">
      <eGenericType eClassifier="#//EEList">
        <eTypeArguments eClassifier="#//EObject"/>
      </eGenericType>
    </eOperations>
    <eOperations name="eAllContents">
      <eGenericType eClassifier="#//ETreeIterator">
        <eTypeArguments eClassifier="#//EObject"/>
      </eGenericType>
    </eOperations>
    <eOperations name="eCrossReferences">
      <eGenericType eClassifier="#//EEList">
        <eTypeArguments eClassifier="#//EObject"/>
      </eGenericType>
    </eOperations>
    <eOperations name="eGet">
      <eGenericType eTypeParameter="#//EObject/eGet/T"/>
      <eTypeParameters name="T"/>
      <eParameters name="feature">
        <eGenericType eClassifier="#//EStructuralFeature">
          <eTypeArguments/>
          <eTypeArguments eTypeParameter="#//EObject/eGet/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="eGet">
      <eGenericType eTypeParameter="#//EObject/eGet.1/T"/>
      <eTypeParameters name="T"/>
      <eParameters name="feature">
        <eGenericType eClassifier="#//EStructuralFeature">
          <eTypeArguments/>
          <eTypeArguments eTypeParameter="#//EObject/eGet.1/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="resolve" eType="#//EBoolean"/>
    </eOperations>
    <eOperations name="eSet">
      <eTypeParameters name="T"/>
      <eParameters name="feature">
        <eGenericType eClassifier="#//EStructuralFeature">
          <eTypeArguments/>
          <eTypeArguments eTypeParameter="#//EObject/eSet/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="newValue">
        <eGenericType eTypeParameter="#//EObject/eSet/T"/>
      </eParameters>
    </eOperations>
    <eOperations name="eIsSet" eType="#//EBoolean">
      <eParameters name="feature">
        <eGenericType eClassifier="#//EStructuralFeature">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="eUnset">
      <eParameters name="feature">
        <eGenericType eClassifier="#//EStructuralFeature">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="eInvoke" eExceptions="#//EInvocationTargetException">
      <eGenericType eTypeParameter="#//EObject/eInvoke/T"/>
      <eTypeParameters name="T"/>
      <eParameters name="operation">
        <eGenericType eClassifier="#//EOperation">
          <eTypeArguments/>
          <eTypeArguments eTypeParameter="#//EObject/eInvoke/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="arguments">
        <eGenericType eClassifier="#//EEList">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EOperation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueParameterNames UniqueTypeParameterNames NoRepeatingVoid"/>
    </eAnnotations>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//EObject"/>
    </eTypeParameters>
    <eTypeParameters name="V"/>
    <eOperations name="getOperationID" eType="#//EInt"/>
    <eOperations name="isOverrideOf" eType="#//EBoolean">
      <eParameters name="someOperation">
        <eGenericType eClassifier="#//EOperation">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainingClass" changeable="false"
        transient="true" resolveProxies="false" eOpposite="#//EClass/eOperations">
      <eGenericType eClassifier="#//EClass">
        <eTypeArguments eTypeParameter="#//EOperation/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeParameters" upperBound="-1"
        eType="#//ETypeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eParameters" upperBound="-1"
        containment="true" resolveProxies="false" eOpposite="#//EParameter/eOperation">
      <eGenericType eClassifier="#//EParameter">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eExceptions" upperBound="-1"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
        <details key="suppressedUnsetVisibility" value="true"/>
      </eAnnotations>
      <eGenericType eClassifier="#//EClassifier">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGenericExceptions" upperBound="-1"
        eType="#//EGenericType" unsettable="true" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
        <details key="suppressedUnsetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//ETypedElement">
      <eTypeArguments eTypeParameter="#//EOperation/V"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EPackage" eSuperTypes="#//ENamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="WellFormedNsURI WellFormedNsPrefix UniqueSubpackageNames UniqueClassifierNames UniqueNsURIs"/>
    </eAnnotations>
    <eOperations name="getEClassifier">
      <eGenericType eClassifier="#//EClassifier">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="name" eType="#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsURI" eType="#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsPrefix" eType="#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFactoryInstance" lowerBound="1"
        eType="#//EFactory" transient="true" resolveProxies="false" eOpposite="#//EFactory/ePackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClassifiers" upperBound="-1"
        containment="true" eOpposite="#//EClassifier/ePackage">
      <eGenericType eClassifier="#//EClassifier">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eSubpackages" upperBound="-1"
        eType="#//EPackage" containment="true" eOpposite="#//EPackage/eSuperPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eSuperPackage" eType="#//EPackage"
        changeable="false" transient="true" eOpposite="#//EPackage/eSubpackages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EParameter">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eOperation" changeable="false"
        transient="true" resolveProxies="false" eOpposite="#//EOperation/eParameters">
      <eGenericType eClassifier="#//EOperation">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//ETypedElement">
      <eTypeArguments eTypeParameter="#//EParameter/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReference">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ConsistentOpposite SingleContainer ConsistentKeys ConsistentUnique ConsistentContainer"/>
    </eAnnotations>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//EObject"/>
    </eTypeParameters>
    <eTypeParameters name="V"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" eType="#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="container" eType="#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolveProxies" eType="#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eOpposite">
      <eGenericType eClassifier="#//EReference">
        <eTypeArguments/>
        <eTypeArguments eTypeParameter="#//EReference/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eReferenceType" lowerBound="1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//EClass">
        <eTypeArguments eTypeParameter="#//EReference/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eKeys" upperBound="-1">
      <eGenericType eClassifier="#//EAttribute">
        <eTypeArguments eTypeParameter="#//EReference/C"/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//EStructuralFeature">
      <eTypeArguments eTypeParameter="#//EReference/C"/>
      <eTypeArguments eTypeParameter="#//EReference/V"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeature" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidDefaultValueLiteral"/>
    </eAnnotations>
    <eTypeParameters name="C">
      <eBounds eClassifier="#//EObject"/>
    </eTypeParameters>
    <eTypeParameters name="V"/>
    <eOperations name="getFeatureID" eType="#//EInt"/>
    <eOperations name="getContainerClass">
      <eGenericType eClassifier="#//EJavaClass">
        <eTypeArguments eTypeParameter="#//EStructuralFeature/C"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeable" eType="#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volatile" eType="#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueLiteral" eType="#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" changeable="false"
        volatile="true" transient="true" derived="true">
      <eGenericType eTypeParameter="#//EStructuralFeature/V"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unsettable" eType="#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainingClass" changeable="false"
        transient="true" resolveProxies="false" eOpposite="#//EClass/eStructuralFeatures">
      <eGenericType eClassifier="#//EClass">
        <eTypeArguments eTypeParameter="#//EStructuralFeature/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//ETypedElement">
      <eTypeArguments eTypeParameter="#//EStructuralFeature/V"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETypedElement" abstract="true" eSuperTypes="#//ENamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidLowerBound ValidUpperBound ConsistentBounds ValidType"/>
    </eAnnotations>
    <eTypeParameters name="C"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" eType="#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" volatile="true"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
        <details key="suppressedUnsetVisibility" value="true"/>
      </eAnnotations>
      <eGenericType eClassifier="#//EClassifier">
        <eTypeArguments eTypeParameter="#//ETypedElement/C"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGenericType" eType="#//EGenericType"
        volatile="true" unsettable="true" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
        <details key="suppressedUnsetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBigDecimal" instanceClassName="java.math.BigDecimal">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#decimal"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBigInteger" instanceClassName="java.math.BigInteger">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#integer"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBoolean" instanceClassName="boolean">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#boolean"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBooleanObject" instanceClassName="java.lang.Boolean">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EBoolean"/>
      <details key="name" value="EBoolean:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EByte" instanceClassName="byte">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#byte"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EByteArray" instanceClassName="byte[]">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#hexBinary"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EByteObject" instanceClassName="java.lang.Byte">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EByte"/>
      <details key="name" value="EByte:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EChar" instanceClassName="char"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ECharacterObject" instanceClassName="java.lang.Character">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EChar"/>
      <details key="name" value="EChar:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EDate" instanceClassName="java.util.Date"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EDiagnosticChain" instanceClassName="org.eclipse.emf.common.util.DiagnosticChain"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EDouble" instanceClassName="double">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#double"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EDoubleObject" instanceClassName="java.lang.Double">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EDouble"/>
      <details key="name" value="EDouble:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EEList" instanceClassName="org.eclipse.emf.common.util.EList"
      serializable="false">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EEnumerator" instanceClassName="org.eclipse.emf.common.util.Enumerator"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureMap" instanceClassName="org.eclipse.emf.ecore.util.FeatureMap"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureMapEntry" instanceClassName="org.eclipse.emf.ecore.util.FeatureMap$Entry"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFloat" instanceClassName="float">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#float"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EFloatObject" instanceClassName="java.lang.Float">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EFloat"/>
      <details key="name" value="EFloat:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EInt" instanceClassName="int">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#int"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EIntegerObject" instanceClassName="java.lang.Integer">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EInt"/>
      <details key="name" value="EInt:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EJavaClass" instanceClassName="java.lang.Class">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EJavaObject" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ELong" instanceClassName="long">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#long"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ELongObject" instanceClassName="java.lang.Long">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="ELong"/>
      <details key="name" value="ELong:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EMap" instanceClassName="java.util.Map"
      serializable="false">
    <eTypeParameters name="K"/>
    <eTypeParameters name="V"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EResource" instanceClassName="org.eclipse.emf.ecore.resource.Resource"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EResourceSet" instanceClassName="org.eclipse.emf.ecore.resource.ResourceSet"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EShort" instanceClassName="short">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#short"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EShortObject" instanceClassName="java.lang.Short">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EShort"/>
      <details key="name" value="EShort:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EString" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#string"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStringToStringMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ETreeIterator" instanceClassName="org.eclipse.emf.common.util.TreeIterator"
      serializable="false">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGenericType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ConsistentType ConsistentBounds ConsistentArguments"/>
    </eAnnotations>
    <eOperations name="isInstance" eType="#//EBoolean">
      <eParameters name="object" eType="#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eUpperBound" eType="#//EGenericType"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeArguments" upperBound="-1"
        eType="#//EGenericType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eRawType" lowerBound="1"
        changeable="false" transient="true" derived="true">
      <eGenericType eClassifier="#//EClassifier">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eLowerBound" eType="#//EGenericType"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeParameter" eType="#//ETypeParameter"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClassifier">
      <eGenericType eClassifier="#//EClassifier">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETypeParameter" eSuperTypes="#//ENamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBounds" upperBound="-1"
        eType="#//EGenericType" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EInvocationTargetException" instanceClassName="java.lang.reflect.InvocationTargetException"
      serializable="false"/>
</ecore:EPackage>
